# Generated by Django 3.2.6 on 2021-12-08 12:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cat_name', models.CharField(default='', max_length=50, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='ProductModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='', max_length=1000, null=True)),
                ('description', models.TextField(default='', null=True)),
                ('asin', models.CharField(default='', max_length=15, null=True)),
                ('cats', models.ForeignKey(default='', null=True, on_delete=django.db.models.deletion.CASCADE, to='API.category')),
            ],
        ),
        migrations.CreateModel(
            name='ReviewData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('asin', models.CharField(default='', max_length=10, null=True)),
                ('reviewText', models.TextField(default='', null=True)),
                ('status', models.CharField(default='', max_length=100, null=True)),
                ('reviewTime', models.CharField(default='', max_length=50, null=True)),
                ('rating', models.DecimalField(decimal_places=2, default=0.0, max_digits=3)),
                ('prods', models.ForeignKey(default='', null=True, on_delete=django.db.models.deletion.CASCADE, to='API.productmodel')),
            ],
        ),
        migrations.CreateModel(
            name='Reviewer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reviewerName', models.CharField(default='', max_length=1000, null=True)),
                ('reviewerID', models.CharField(default='', max_length=15, null=True)),
                ('reviewdata', models.ForeignKey(default='', null=True, on_delete=django.db.models.deletion.CASCADE, to='API.reviewdata')),
            ],
        ),
        migrations.CreateModel(
            name='Images',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image_high', models.CharField(default='', max_length=1000, null=True)),
                ('image_low', models.CharField(default='', max_length=1000, null=True)),
                ('prods', models.ForeignKey(default='', null=True, on_delete=django.db.models.deletion.CASCADE, to='API.productmodel')),
            ],
        ),
    ]
