# Generated by Django 3.2.6 on 2022-02-07 10:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('API', '0003_reviewer_reviewtime'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='reviewer',
            name='reviewTime',
        ),
    ]
